In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# 3x3 matrix
A = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print(A, '\n')

# compute average of each column
avg = np.mean(A, axis=0)
print(avg, '\n')

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

[2. 5. 8.] 



In [4]:
# 3x3 matrix
A = np.array([[1, 2, 3], [3, 4, 5], [5, 3, 1]])
print(A, '\n')

# multiply matrix by 2
A = A * 2
print(A, '\n')

# compute average
avg = np.mean(A, axis=0)
print(avg, '\n')

[[1 2 3]
 [3 4 5]
 [5 3 1]] 

[[ 2  4  6]
 [ 6  8 10]
 [10  6  2]] 

[6. 6. 6.] 



In [5]:
# 3x3 matrix
A = np.array([[1, 2, 3], [3, 4, 5], [5, 3, 1]])
print(A, '\n')

# add [1, 2, 3] to each sample
A = A + np.array([1, 2, 3])
print(A, '\n')

# average
avg = np.mean(A, axis=0)
print(avg, '\n')

[[1 2 3]
 [3 4 5]
 [5 3 1]] 

[[2 4 6]
 [4 6 8]
 [6 5 4]] 

[4. 5. 6.] 



In [6]:
def reshape(x):
  """return x_reshaped as a flattened vector of the multi-dimensional array x"""
  x_reshaped = x.reshape(x.shape[0] * x.shape[1])
  return x_reshaped

In [7]:
# matrix
d = np.array([
    [1, 2],
    [5, 4]
])

# covariance matrix of d
cov = np.cov(d)
print(cov, '\n')

[[ 0.5 -0.5]
 [-0.5  0.5]] 



---

In [8]:
# dataset list
dataset = [1, 2, 3, 2]

# variance
var = np.var(dataset)
print(var, '\n')

# standard deviation
std = np.std(dataset)
print(std, '\n')

# add each element of dataset with 1
for i in range(len(dataset)):
  dataset[i] = dataset[i] + 1
print(dataset, '\n')

# new variance
var = np.var(dataset)
print(var, '\n')

0.5 

0.7071067811865476 

[2, 3, 4, 3] 

0.5 



In [9]:
# dataset list
dataset = [1, 2, 3, 2]

# multiply each element of dataset by 2
for i in range(len(dataset)):
    dataset[i] = dataset[i] * 2
print(dataset, '\n')

# new variance
var = np.var(dataset)
print(var, '\n')

[2, 4, 6, 4] 

2.0 



---

In [10]:
# 2x2 matrix dataset
dataset = [[1, 2], [5, 4]]
print(dataset, '\n')

# covariance matrix
cov = np.cov(dataset)
print(cov, '\n')

[[1, 2], [5, 4]] 

[[ 0.5 -0.5]
 [-0.5  0.5]] 



In [11]:
# 2x2 matrix dataset
dataset = np.array([
    [3, 2],
    [2, 4]
    ])
print(dataset, '\n')

# multiply each element of dataset by 2
dataset = dataset * 2
print(dataset, '\n')

# covariance matrix
cov = np.cov(dataset)
print(cov, '\n')

[[3 2]
 [2 4]] 

[[6 4]
 [4 8]] 

[[ 2. -4.]
 [-4.  8.]] 

