In [18]:
import numpy as np
from sympy import *

In [19]:
# symbols (x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = sin(x)*e^(y*z^2)
f = sin(x)*exp(y*z**2)

# diff in respect to each variable
dfdx = f.diff(x)
dfdy = f.diff(y)
dfdz = f.diff(z)

# output
dfdx

exp(y*z**2)*cos(x)

In [20]:
dfdy


z**2*exp(y*z**2)*sin(x)

In [21]:
dfdz

2*y*z*exp(y*z**2)*sin(x)

---
## Practicing partial differentiation

In [22]:
# symbols(x, y)
x, y, m = symbols('x y m')

# f(x, y) = pi*x^3 + x*y^2 +m*y^4
f = pi*x**3 + x*y**2 + m*y**4

dfdx = f.diff(x)
dfdy = f.diff(y)

dfdx

3*pi*x**2 + y**2

In [23]:
dfdy

4*m*y**3 + 2*x*y

In [24]:
# symbols(x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = x^2*y + y^2*z + z^2*x
f = x**2*y + y**2*z + z**2*x

dfdx = f.diff(x)
dfdy = f.diff(y)
dfdz = f.diff(z)

dfdx

2*x*y + z**2

In [25]:
dfdy

x**2 + 2*y*z

In [26]:
dfdz

2*x*z + y**2

In [27]:
# symbols(x, y, z)
x, y, z = symbols('x y z')

# f(x) = e^2x sin(y)z^2+cos(z)e^x*e^y
f = exp(2*x)*(sin(y)*z**2) + cos(z)*exp(x)*exp(y)

dfdx = f.diff(x)
dfdy = f.diff(y)
dfdz = f.diff(z)

dfdx

2*z**2*exp(2*x)*sin(y) + exp(x)*exp(y)*cos(z)

In [28]:
dfdy

z**2*exp(2*x)*cos(y) + exp(x)*exp(y)*cos(z)

In [29]:
dfdz

2*z*exp(2*x)*sin(y) - exp(x)*exp(y)*sin(z)

In [31]:
# symbols(x, y, t)
x, y, t = symbols('x y t')

# f(x, y) = sqrt(x)/y
f = sqrt(t)/sin(t)

dfdt = f.diff(t)
dfdt


-sqrt(t)*cos(t)/sin(t)**2 + 1/(2*sqrt(t)*sin(t))

In [43]:
# symbols (x, y, z, t)
x, y, z, t = symbols('x y z t')

# f(x, y, z,) = cos(x)sin(y)e^2z
f = cos(x)*sin(y)*exp(2*z)

f = f.subs({x: t-1, y: t, z: t**2})
dfdt = f.diff(t)
dfdt

4*t*exp(2*t**2)*sin(t)*cos(t - 1) - exp(2*t**2)*sin(t)*sin(t - 1) + exp(2*t**2)*cos(t)*cos(t - 1)

---
## Calculating the Jacobian

In [44]:
# symbols (x, y)
x, y = symbols('x y')

# f(x,y) = x^2y + 3/4xy + 10
f = x**2*y + 3/4*x*y + 10

# calculate jacobian row vector j
j = [f.diff(x), f.diff(y)]
j

[2*x*y + 0.75*y, x**2 + 0.75*x]

In [49]:
# symbols (x, y)
x, y = symbols('x y')

# f(x,y)) = e^xcos(y)+ xe^(3y)-2
f = exp(x)*cos(y) + x*exp(3*y) - 2

# calculate jacobian row vector j
j = [f.diff(x), f.diff(y)]

# print in markdown
print(j)

[exp(x)*cos(y) + exp(3*y), 3*x*exp(3*y) - exp(x)*sin(y)]


In [50]:
# symbols (x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = e^xcos(y) + x^2y^2z^2
f = exp(x)*cos(y) + (x**2)*(y**2)*(z**2)

# calculate jacobian row vector j
j = [f.diff(x), f.diff(y), f.diff(z)]
print(j)

[2*x*y**2*z**2 + exp(x)*cos(y), 2*x**2*y*z**2 - exp(x)*sin(y), 2*x**2*y**2*z]


In [53]:
# symbols (x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = x^2 + 3(e^y)(e^z)+cos(x)sin(z)
f = x**2 + 3*(exp(y)*exp(z)) + cos(x)*sin(z)

# calculate jacobian row vector j and evaluate at (0, 0, 0)
j = [f.diff(x), f.diff(y), f.diff(z)]

# substitute values for x, y, z with 0
j = [i.subs({x: 0, y: 0, z: 0}) for i in j]
print(j)

[0, 3, 4]


In [56]:
# symbols (x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = x(e^y)cos(z) + 5x^2sin(y)e^z
f = x*(exp(y)*cos(z)) + 5*(x**2)*sin(y)*exp(z)

# calculate jacobian row vector j and evaluate at (0, 0, 0)
j = [f.diff(x), f.diff(y), f.diff(z)]

# substitute values for x, y, z with 0
j = [i.subs({x: 0, y: 0, z: 0}) for i in j]

# convert to numpy array
j = np.array(j)
print(j)

[1 0 0]


---

## application on jacobian factorization

In [58]:
# symbols (x, y)

u = x - 2*y
v = 3*y - 2*x

# calculate jacobian row vector j
ju_x = u.diff(x)
ju_y = u.diff(y)
jv_x = v.diff(x)
jv_y = v.diff(y)

# convert to 2x2 numpy array
j = np.array([[ju_x, ju_y], [jv_x, jv_y]])
print(j)

[[1 -2]
 [-2 3]]


In [59]:
# symbols (x, y)

u = x**2 - y**2
v = 2*x*y

# calculate jacobian row vector j
ju_x = u.diff(x)
ju_y = u.diff(y)
jv_x = v.diff(x)
jv_y = v.diff(y)

# convert to 2x2 numpy array
j = np.array([[ju_x, ju_y], [jv_x, jv_y]])
print(j)

[[2*x -2*y]
 [2*y 2*x]]


In [66]:
# symbols (x, y)
x, y, z = symbols('x y z')

u = 2*x + 3*y
v = cos(x)*sin(z)
w = exp(x)*exp(y)*exp(z)

# calculate jacobian row vector j
ju_x = u.diff(x)
ju_y = u.diff(y)
ju_z = u.diff(z)
jv_x = v.diff(x)
jv_y = v.diff(y)
jv_z = v.diff(z)
jw_x = w.diff(x)
jw_y = w.diff(y)
jw_z = w.diff(z)

# convert to 2x2 numpy array
j = np.array([[ju_x, ju_y], [jv_x, jv_y]])
print(j)

[[2 3 0]
 [0 0 1]
 [1 1 1]]


In [64]:
# symbols (a, b, c, d, x, y), where a, b, c, d are constants
a, b, c, d, x, y = symbols('a b c d x y')

u = a*x + b*y
v = c*x + d*y

# calculate jacobian row vector j
ju_x = u.diff(x)
ju_y = u.diff(y)
jv_x = v.diff(x)
jv_y = v.diff(y)

# convert to 2x2 numpy array
j = np.array([[ju_x, ju_y], [jv_x, jv_y]])
print(j)

[[a b]
 [c d]]


In [76]:
# symbols (x, y)
x, y, z = symbols('x y z')

u = 9*(x**2)*(y**2) + z*exp(x)
v = x*y+(x**2)*(y**3)+2*z
w = cos(x)*sin(z)*exp(y)

# calculate jacobian row vector j
ju_x = u.diff(x)
ju_y = u.diff(y)
ju_z = u.diff(z)
jv_x = v.diff(x)
jv_y = v.diff(y)
jv_z = v.diff(z)
jw_x = w.diff(x)
jw_y = w.diff(y)
jw_z = w.diff(z)

# substitute values for x, y, z with 0
j = np.array([
    [
    ju_x.subs({x: 0, y: 0, z: 0}),
    ju_y.subs({x: 0, y: 0, z: 0}),
    ju_z.subs({x: 0, y: 0, z: 0})
    ],

    [
    jv_x.subs({x: 0, y: 0, z: 0}),
    jv_y.subs({x: 0, y: 0, z: 0}),
    jv_z.subs({x: 0, y: 0, z: 0})
    ],
    
    [
    jw_x.subs({x: 0, y: 0, z: 0}),
    jw_y.subs({x: 0, y: 0, z: 0}),
    jw_z.subs({x: 0, y: 0, z: 0})
    ]
])

print(j)

[[0 0 1]
 [0 0 2]
 [0 0 1]]


In [72]:
# symbols (r, theta, phi)
r, theta, phi, = symbols('r theta phi')

u = r*cos(theta)*sin(phi)
v = r*sin(theta)*sin(phi)
w = r*cos(phi)

# calculate jacobian row vector j
ju_r = u.diff(r)
ju_theta = u.diff(theta)
ju_phi = u.diff(phi)
jv_rju_r = v.diff(r)
jv_thetaju_theta = v.diff(theta)
jv_phi = v.diff(phi)
jw_rju_r = w.diff(r)
jw_thetaju_theta = w.diff(theta)
jw_phi = w.diff(phi)

# convert to 3x3 numpy array
j = np.array([
    [ju_r, ju_theta, ju_phi
],
    [jv_rju_r, jv_thetaju_theta, jv_phi
],
    [jw_rju_r, jw_thetaju_theta, jw_phi
]
])

print(j)

[[sin(phi)*cos(theta) -r*sin(phi)*sin(theta) r*cos(phi)*cos(theta)]
 [sin(phi)*sin(theta) r*sin(phi)*cos(theta) r*sin(theta)*cos(phi)]
 [cos(phi) 0 -r*sin(phi)]]


---
## Hessian Matrix

In [93]:
# symbols (x, y, z)
x, y, = symbols('x y')

# f(x) = x^2 + y^2
f = x**2 + y**2

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)

# convert to 2x2 numpy array
j = [ju_x, ju_y]
print(j)



[2*x, 2*y]


In [95]:
import numpy as np
from sympy import *

# symbols (x, y, z)
x, y, z = symbols('x y z')

f = (x**2)*y*z

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)
ju_z = f.diff(z)

j = [ju_x, ju_y, ju_z]
print(j, '\n')

# calculate hessian matrix h in respect to x, y, z
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y),
    ju_x.diff(z)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y),
    ju_y.diff(z)
    ],

    [
    ju_z.diff(x),
    ju_z.diff(y),
    ju_z.diff(z)
    ]
])
print(h, '\n')

[2*x*y*z, x**2*z, x**2*y]
[[2*y*z 2*x*z 2*x*y]
 [2*x*z 0 x**2]
 [2*x*y x**2 0]]


In [96]:
# symbols (x, y)
x, y = symbols('x y')

# f(x) = (x^3)y + x +2y
f = (x**3)*y + x + 2*y

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)

# calculate hessian matrix h in respect to x, y
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y)
    ]
])

print(h)

[[6*x*y 3*x**2]
 [3*x**2 0]]


In [97]:
# symbols (x, y)
x, y = symbols('x y')

# f(x) = (e^x) * cos(y)
f = exp(x)*cos(y)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)

# calculate hessian matrix h in respect to x, y
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y)
    ]
])

print(h)

[[exp(x)*cos(y) -exp(x)*sin(y)]
 [-exp(x)*sin(y) -exp(x)*cos(y)]]


In [98]:
# symbols (x, y)
x, y = symbols('x y')

# f(x) = (x^2/2) + xy + (y^2/2)
f = (x**2/2) + x*y + (y**2/2)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)

# calculate hessian matrix h in respect to x, y
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y)
    ]
])

print(h)

[[1 1]
 [1 1]]


In [99]:
# symbols (x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = (x^2)(e^-y)cos(z)
f = (x**2)*exp(-y)*cos(z)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)
ju_z = f.diff(z)

# calculate hessian matrix h in respect to x, y, z
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y),
    ju_x.diff(z)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y),
    ju_y.diff(z)
    ],

    [
    ju_z.diff(x),
    ju_z.diff(y),
    ju_z.diff(z)
    ]
])

print(h)

[[2*exp(-y)*cos(z) -2*x*exp(-y)*cos(z) -2*x*exp(-y)*sin(z)]
 [-2*x*exp(-y)*cos(z) x**2*exp(-y)*cos(z) x**2*exp(-y)*sin(z)]
 [-2*x*exp(-y)*sin(z) x**2*exp(-y)*sin(z) -x**2*exp(-y)*cos(z)]]


In [100]:
# symbols (x, y, z)
x, y, z = symbols('x y z')

# f(x, y, z) = xe^y + (y^2)cos(z)
f = x*exp(y) + (y**2)*cos(z)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)
ju_z = f.diff(z)

# calculate hessian matrix h in respect to x, y, z
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y),
    ju_x.diff(z)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y),
    ju_y.diff(z)
    ],

    [
    ju_z.diff(x),
    ju_z.diff(y),
    ju_z.diff(z)
    ]
])

print(h)

[[0 exp(y) 0]
 [exp(y) x*exp(y) + 2*cos(z) -2*y*sin(z)]
 [0 -2*y*sin(z) -y**2*cos(z)]]


In [ ]:
def jacobian_hessian_xyz(fx): # fx is a function of x, y, z
    # symbols (x, y, z)
    x, y, z = symbols('x y z')
    # f(x, y, z) = fx
    f = fx
    # calculate jacobian row vector j
    ju_x = f.diff(x)
    ju_y = f.diff(y)
    ju_z = f.diff(z)

    # jaobian matrix j
    j = [ju_x, ju_y, ju_z]

    # calculate hessian matrix h in respect to x, y, z
    h = np.array([
        [
        ju_x.diff(x),
        ju_x.diff(y),
        ju_x.diff(z)
        ],

        [
        ju_y.diff(x),
        ju_y.diff(y),
        ju_y.diff(z)
        ],

        [
        ju_z.diff(x),
        ju_z.diff(y),
        ju_z.diff(z)
        ]
    ])
    return j, h

def jacobian_hessian_xy(fx): # fx is a function of x, y
    # symbols (x, y)
    x, y = symbols('x y')
    # f(x, y) = fx
    f = fx
    # calculate jacobian row vector j
    ju_x = f.diff(x)
    ju_y = f.diff(y)

    # jaobian matrix j
    j = [ju_x, ju_y]

    # calculate hessian matrix h in respect to x, y
    h = np.array([
        [
        ju_x.diff(x),
        ju_x.diff(y)
        ],

        [
        ju_y.diff(x),
        ju_y.diff(y)
        ]
    ])
    return j, h


---
## QUIZ

In [101]:
# symbols (x, y, z)
x, y, z = symbols('x y z')
# f(x, y, z) = x^2cos(y) + e^zsin(x)
f = (x**2)*cos(y) + exp(z)*sin(x)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)
ju_z = f.diff(z)

# substitute x = pi, y = pi, z = 1
j = np.array([
    [
    ju_x.subs({x: pi, y: pi, z: 1}),
    ju_y.subs({x: pi, y: pi, z: 1}),
    ju_z.subs({x: pi, y: pi, z: 1})
    ]
])
print(j)

[[-2*pi - E 0 0]]


In [102]:
# symbols (x, y)
x, y= symbols('x y')
# u(x, y) = (x^2)y - cos(x)sin(y)
u = (x**2)*y - cos(x)*sin(y)
# v(x, y) = e^(x+y)
v = exp(x+y)

# calculate jacobian row vector j
ju_x = u.diff(x)
ju_y = u.diff(y)
jv_x = v.diff(x)
jv_y = v.diff(y)

# substitute x = 0, y = pi
j = np.array([
    [
    ju_x.subs({x: 0, y: pi}),
    ju_y.subs({x: 0, y: pi})
    ],

    [
    jv_x.subs({x: 0, y: pi}),
    jv_y.subs({x: 0, y: pi})
    ]
])
print(j)

[[0 1]
 [exp(pi) exp(pi)]]


In [104]:
# symbols (x, y)
x, y= symbols('x y')
# f(x, y) = (x^3)cos(y) + xsin(y)
f = (x**3)*cos(y) - x*sin(y)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)

# calculate hessian matrix h in respect to x, y
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y)
    ]
])

print(h)

[[6*x*cos(y) -3*x**2*sin(y) - cos(y)]
 [-3*x**2*sin(y) - cos(y) -x**3*cos(y) + x*sin(y)]]


In [105]:
# symbols (x, y, z)
x, y, z = symbols('x y z')
# f(x, y, z) = xy+sin(y)sin(z) + (z^3)e^x
f = x*y + sin(y)*sin(z) + (z**3)*exp(x)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)
ju_z = f.diff(z)

# calculate hessian matrix h in respect to x, y, z
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y),
    ju_x.diff(z)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y),
    ju_y.diff(z)
    ],

    [
    ju_z.diff(x),
    ju_z.diff(y),
    ju_z.diff(z)
    ]
])

print(h)

[[z**3*exp(x) 1 3*z**2*exp(x)]
 [1 -sin(y)*sin(z) cos(y)*cos(z)]
 [3*z**2*exp(x) cos(y)*cos(z) 6*z*exp(x) - sin(y)*sin(z)]]


In [110]:
# symbols (x, y, z)
x, y, z = symbols('x y z')
# f(x,y,z) = xycos(z) - sin(x)(e^y)(z^3)
f = x*y*cos(z) - sin(x)*exp(y)*(z**3)

# calculate jacobian row vector j
ju_x = f.diff(x)
ju_y = f.diff(y)
ju_z = f.diff(z)

# calculate hessian matrix h in respect to x, y, z
h = np.array([
    [
    ju_x.diff(x),
    ju_x.diff(y),
    ju_x.diff(z)
    ],

    [
    ju_y.diff(x),
    ju_y.diff(y),
    ju_y.diff(z)
    ],

    [
    ju_z.diff(x),
    ju_z.diff(y),
    ju_z.diff(z)
    ]
])

print(h)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
