In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [32]:
# find eigen vectors of a matrix

# matrix a before transformation
a = np.array([
    [1, 2],
    [3, 4]
    ])
print(a, '\n')

# rotate 2x2 matrix certain degrees
def rotate_matrix(a, theta): # theta in degrees
    theta = np.deg2rad(theta)
    c, s = np.cos(theta), np.sin(theta)
    R = np.array([
        [c, -s],
        [s, c]
        ])
    return np.dot(R, a)

b = rotate_matrix(a, 180)
print(b, '\n')

# find eigen vectors of a matrix
def eigen_vectors(a):
    eigen_values, eigen_vectors = np.linalg.eig(a)
    return eigen_values, eigen_vectors

print(eigen_vectors(a), '\n')
print(eigen_vectors(b), '\n')

# eigen value ratio between a and b
print(eigen_vectors(a)[0]/eigen_vectors(b)[0], '\n')
# eigen vector ratio between a and b
print(eigen_vectors(a)[1]/eigen_vectors(b)[1], '\n')

[[1 2]
 [3 4]] 

[[-1. -2.]
 [-3. -4.]] 

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])) 

(array([ 0.37228132, -5.37228132]), array([[ 0.82456484,  0.41597356],
       [-0.56576746,  0.90937671]])) 

[-1. -1.] 

[[-1. -1.]
 [-1. -1.]] 



In [34]:
# 10x10 random matrix, range 0 to 10 integer
a = np.random.randint(0, 10, (10, 10))
print(a, '\n')

a_det = np.linalg.det(a)
print(a_det, '\n')

a_trans = np.transpose(a)
print(a_trans)

[[9 0 4 2 7 7 4 1 3 2]
 [5 9 7 1 0 9 2 1 5 1]
 [4 5 8 2 5 9 6 8 1 9]
 [0 9 5 4 2 4 2 4 5 3]
 [7 9 0 6 8 7 7 6 7 8]
 [6 4 5 7 9 2 2 6 7 1]
 [3 0 4 6 5 8 6 8 6 6]
 [8 6 0 9 7 7 2 3 3 4]
 [0 8 5 4 2 6 7 1 8 6]
 [2 0 4 4 5 2 4 0 2 6]] 

45583988.999999985 

[[9 5 4 0 7 6 3 8 0 2]
 [0 9 5 9 9 4 0 6 8 0]
 [4 7 8 5 0 5 4 0 5 4]
 [2 1 2 4 6 7 6 9 4 4]
 [7 0 5 2 8 9 5 7 2 5]
 [7 9 9 4 7 2 8 7 6 2]
 [4 2 6 2 7 2 6 2 7 4]
 [1 1 8 4 6 6 8 3 1 0]
 [3 5 1 5 7 7 6 3 8 2]
 [2 1 9 3 8 1 6 4 6 6]]
