In [8]:
import numpy as np
import matplotlib.pyplot as plt
from fractions import Fraction

In [27]:
# characteristic polynomial of a 2x2 square matrix is x^2 -(a+d)x + (ad-bc) = 0
def charpoly(matrix):
    a = matrix[0,0]
    b = matrix[0,1]
    c = matrix[1,0]
    d = matrix[1,1]
    char_poly = np.poly1d([1, -(a+d), (a*d-b*c)])
    return char_poly

# get abc value from polynomial
def poly_abc(poly):
    a = poly[2]
    b = poly[1]
    c = poly[0]
    return a, b, c

# find x1 and x2 from the characteristic polynomial
def quadratic(a, b ,c):
    if a == 0:
        return (-c/b)
    else:
        x1 = (-b + np.sqrt(b**2 - 4*a*c))/(2*a)
        x2 = (-b - np.sqrt(b**2 - 4*a*c))/(2*a)
        return x1, x2

In [31]:
A = np.array([
    [1,0],
    [0,2]])

B = charpoly(A)
print(B, '\n')

b1, b2 = quadratic(poly_abc(B)[0], poly_abc(B)[1], poly_abc(B)[2])
print(b1, b2)

   2
1 x - 3 x + 2 

2.0 1.0


In [18]:
C = np.array([
    [1,0],
    [0,2]])

# eigenvector and eigenvalue of C
eigval, eigvec = np.linalg.eig(C)
print(eigval, '\n')
print(eigvec, '\n')

[1. 2.] 

[[1. 0.]
 [0. 1.]] 



In [20]:
D = np.array([
    [3, 4],
    [0, 5]])

E = charpoly(D)
print(E)

print(quadratic(1, -8, 15))

   2
1 x - 8 x + 15
(5.0, 3.0)


In [4]:
F = np.array([
    [3, 4],
    [0, 5]])

eig_vec_F, eig_val_F = np.linalg.eig(F)
print(eig_val_F)
print(eig_vec_F)

[[1.         0.89442719]
 [0.         0.4472136 ]]
[3. 5.]


In [25]:
G = np.array([
    [1, 0],
    [-1, 4]])

H = charpoly(G)
print(H)

print(quadratic(1, -5, 4))

   2
1 x - 5 x + 4
(4.0, 1.0)


---

In [35]:
T = np.array([
    [6, -1],
    [2, -3]
    ])

C = np.array([
    [1, 1],
    [1, 2]
    ])

# matrix D = C^-1 * TC
D = np.linalg.inv(C) * T * C

# diagonalize matrix D
eig_val_D, eig_vec_D = np.linalg.eig(D)
print(eig_val_D)
print(eig_vec_D)

[11.88819442 -5.88819442]
[[ 0.99380775 -0.05581564]
 [-0.11111325  0.99844109]]


In [9]:
m = np.array([
    [4, -5, 6],
    [7, -8 , 6],
    [3/2, -1/2, -2]
    ])

# find eigen
eig_val_m, eig_vec_m = np.linalg.eig(m)
print(eig_val_m, '\n')
print(eig_vec_m, '\n')

[ 1. -4. -3.] 

[[-0.6882472  -0.66666667  0.40824829]
 [-0.6882472  -0.66666667 -0.40824829]
 [-0.22941573  0.33333333 -0.81649658]] 



TypeError: object of type 'numpy.float64' has no len()