In [1]:
import numpy as np

## Non-square matrix multiplication
#### 75%

In [15]:
alpha = np.array([
    [2],
    [0]
])

beta = np.array([
    [1, 1, 0]])

charlie = np.dot(alpha, beta)
print(charlie)

[[2 2 0]
 [0 0 0]]


In [2]:
# matrix multiplication

A = np.array([
    [1, 2, 3], 
    [4, 0, 1]])

B = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]])

# matrix C = A * B
C = np.dot(A, B)
print(C)

[[4 3 5]
 [5 4 1]]


In [13]:
# 4x1 matrix multiplied by 1x4 matrix
D = np.array([
    [2, 4, 5, 6]])

E = np.array([
    [1],
    [3],
    [2],
    [1]])

F1 = np.dot(D, E)
F2 = np.dot(E, D)
print(F1)
print(F2)


# it's not associative, be careful

[[30]]
[[ 2  4  5  6]
 [ 6 12 15 18]
 [ 4  8 10 12]
 [ 2  4  5  6]]


In [11]:
# 4x1 matrix multiplied by 1x4 matrix
G = np.array([
    [2, -1],
    [0, 3],
    [1, 0]])

H = np.array([
    [0, 1, 4, -1],
    [-2, 0, 0, 2]])

I = np.dot(G ,H)
print(I)

[[ 2  2  8 -4]
 [-6  0  0  6]
 [ 0  1  4 -1]]


In [12]:
# 2x2 matrix multiplied by 3x2 matrix

J = np.array([
    [1, 0],
    [0, 1]])

K = np.array([
    [1, 2, 3],
    [4, 5, 6]])

L = np.dot(J, K)
print(L)

[[1 2 3]
 [4 5 6]]


In [24]:
# random 4x3 matrix, integer numbers only
M = np.random.randint(0, 10, (4, 3))
print(M, '\n')

# transpose of M
N = np.transpose(M)
print(N)

[[2 1 3]
 [3 3 0]
 [6 6 6]
 [1 2 7]] 

[[2 3 6 1]
 [1 3 6 2]
 [3 0 6 7]]


---

##  Using non-square matrices to do a projection

In [17]:
# matrix projection

# direction s
s = np.array([
    [4/13],
    [-3/13],
    [-12/13]])

r = np.array([
    [6],
    [2],
    [3]])

# projection of s onto r
p = np.dot(s, r)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)